sudo: false
language: python
python: 2.7

addons:
  apt:
    packages:
    - gnupg

env:
    - TOX_ENV=pyflakes
    - TOX_ENV=license
    - TOX_ENV=py26-twcurrent
    - TOX_ENV=py27-twcurrent
    - TOX_ENV=py26-twtrunk
    - TOX_ENV=py27-twtrunk
    - TOX_ENV=py26-tw150
    - TOX_ENV=py27-tw150

install:
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: true