sudo: false
language: python
python: 2.7

addons:
  apt:
    packages:
    - gnupg

env:
    - TOX_ENV=pyflakes
    - TOX_ENV=license
    - TOX_ENV=py26
    - TOX_ENV=py27


install:
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: true