#!/bin/bash
# Copyright (c) The SimpleFIN Team
# See LICENSE for details.

set -e

account_number=$(curl ${DATASTORE_URL}/account_number?prompt=Account%20Number%3F)
echo "Your account number is $account_number"
